### ISSUE TITLE
Change "Re-colour chart from Cells"

### ISSUE THREAD

**Issue by Harrigan-Davenport** [Conjoint-ly/excel-plugin#3]
The current functionality needs to be expanded upon. The button should stay named as `Re-colour chart from cells`.

![image](https://user-images.githubusercontent.com/66200950/86296840-e5ac4f00-bc4d-11ea-98c1-557e875db3ec.png)

When clicked, the button should change the colors of the selected graph to the background colors of the data cells that it is dependent on.

When selected, the button should open a modal dialog box that has options for where to apply the colors, as well as what to do with the labels of the chart.

![image](https://user-images.githubusercontent.com/66200950/86296908-15f3ed80-bc4e-11ea-962f-097ad92ed542.png)

The default selected values for colors should be `Fill`, `Lines`, `Marker` and for label formatting should be `Value`.

When dark colors are applied to the graph, the label color should be changed to white to make it easier to see.

**Comment by jumpingrabbit** [comment]
### My comments on this functionality:

- [x] Conversion to white text colour (where background of cell is darker), should be applied to the cell directly (before the chart starts recolouring. Nice to have is a checkbox in the modal window (`Ensure white text on darker backgrounds`), which is checked by default.
- [x] By default, the checkbox for `Label formatting`: `Series` should be unchecked.
- [x] The function should update series colours based on the first column (so that the legend is updated correctly)
- [ ] Add one more checkbox under `Apply selected colours to:` `Background of labels` and use that to colour the background of the labels. It should be checked by default for line charts (and unchecked by default for bar charts and other types of charts). Example output:

![Example background for the top label](https://user-images.githubusercontent.com/13073856/88998024-73a25500-d334-11ea-85be-c195c1054f22.png)

**Comment by Harrigan-Davenport** [comment]
- [x] The labels are currently defaulted to the position `Outside end`. It would be ideal if they are instead defaulted to the position `Center`.

**Comment by Harrigan-Davenport** [comment]
- [x] The comment above `Add one more checkbox under Apply selected colours to: Background of labels and use that to colour the background of the labels. It should be checked by default for line charts (and unchecked by default for bar charts and other types of charts)`

The defaults seems to have been done backwards (defaults for bar, not defaults for line). This needs to be the other way around

**Comment by Harrigan-Davenport** [comment]
- [x] The first issue is with the option ensure white text on darker backgrounds. We have noticed that often this does not work as intended. When we run the function we see that the font is changed to white for an instant, then quickly reverts back to black. We think this might be because there is a change to the text formatting that occurs after the font colour is set, which overrides the white font? 

- [x] The second issue is that whenever Recolour chart from cells is run twice (To update a colour change for instance), a grey border appears on the charts, which we do not want. To

**Comment by Harrigan-Davenport** [comment]
**Bug to be fixed**
- [ ] Currently there is a bug where the last value is not set to white when recoloring occurs. This happens when the first value in a column is empty. The attached image shows an example of this occurring 
![image](https://user-images.githubusercontent.com/66200950/93036080-eb350500-f692-11ea-9a32-bfd99f889df5.png)

**New Functionality**
- [ ] Within the modal dialogue box we would like there to be, an option to specify the font size for the graph, under the _Label _formatting__ tab

- [ ] It would be ideal if the pop up modal box could remember your which options you had previously ticked. This way if you were working on multiple charts within one work book you could set up the options once then use the function multiple times
